### ISSUE TITLE
Annotations should allow ElementType=FIELD for use in singleton enums.

### ISSUE THREAD

**Issue by raptor494** [zhong-j-yu/rekex#8] opened 2021-09-27 17:04 UTC
When I try to add an @Str or @Ch annotation to an enum field, I get "Syntax error: Type annotations are illegal here."
This is probably because those annotations are not declared with @Target including ElementType.FIELD (for enum fields)
<img width="687" alt="Screen Shot 2021-09-27 at 12 03 15 PM" src="https://user-images.githubusercontent.com/39534148/134953898-849bb0f1-5aa5-42d7-b6c1-de38226d74f4.png">

**Comment by zhong-j-yu** [comment] 2021-09-27 17:17
Sorry about that. Which version of Java are you using?

I was aware of the ambiguity of type annotation on enum field; but it worked (on my machine:)

**Comment by zhong-j-yu** [comment] 2021-09-27 17:19
https://github.com/zhong-j-yu/rekex/blob/main/doc/note-misc.txt
>If a enum field is annotated with an anno of @Target=Type_USE, it's not clear what happens.
>Javac allows it, so it appears that it applies on the type of the field.
>But field.getAnnotatedType() does not contain the anno.
>And field.getDeclaredAnnotations() does contain the anno.

**Comment by zhong-j-yu** [comment] 2021-09-27 18:16
I think I understand the problem. It is your IDE that reports the error. Since JLS isn't clear on this issue, the IDE cannot be blamed for it. Thanks for reporting.

The issue is fixed in version 1.1.1 - could you try again and see if it works?

**Comment by zhong-j-yu** [comment] 2021-09-29 20:00
Hi @raptor494 , if you have no objections, I'll close this issue as fixed in 24 hours.

**Comment by zhong-j-yu** [comment] 2021-09-30 14:13
Fixed and available since v1.1.1.

**Closed by zhong-j-yu** 2021-09-30 14:13 UTC
Labels: enhancement
